Update JENKINSFILE_agentes

diff --git a/JENKINSFILE_agentes b/JENKINSFILE_agentes
--- a/JENKINSFILE_agentes
+++ b/JENKINSFILE_agentes
@@ -29,9 +29,9 @@ pipeline {
         stage('Parallel') {
             parallel {
 
-                // agent2: REST
+                // agent1: REST
                 stage('Rest') {
-                    agent { label 'agent2' }
+                    agent { label 'agent1' }
                     steps {
                         echo 'REST STAGE'
                         catchError(buildResult: 'UNSTABLE', stageResult: 'FAILURE'){
@@ -71,58 +71,33 @@ pipeline {
                     }
                 }
 
-                // agent2: UNIT + COBERTURA (secuencial)
-                stage('Unit & Coverage') {
+                stage('Unit') {
                     agent { label 'agent2' }
-                    stages {
-
-                        stage('Unit') {
-                            steps {
-                                echo 'UNIT STAGE'
-                                script {
-                                    if (!unitTestsExecuted) {
-                                        unitTestsExecuted = true
-                                        // Pytest no tiene la posibilidad de retornar exit=0 cuando algún test falla por lo que abortaría
-                                        // el pipeline. Con catchError se captura la salida que devuelve pytest y permite
-                                        // seguir con la ejecución del pipeline si falla algún test
-                                        catchError(buildResult: 'UNSTABLE', stageResult: 'FAILURE'){
-                                            unstash name:'code'
-                                            sh '''
-                                                hostname
-                                                echo ${WORKSPACE}
-                                                export PYTHONPATH=${WORKSPACE}
-                                                coverage run --branch --source=app --omit=app/__init__.py,app/api.py -m pytest --junitxml=result-unit.xml test/unit
-                                            '''
-                                            junit 'result-unit.xml'
-                                            stash name:'unit-results', includes:'result-unit.xml,.coverage'
-                                        }
-                                    } else {
-                                        echo "El stage ya se ha ejecutado"
-                                    }
-                                }
-                                // Limpia el workspace del agent al final de la ejecucion
-                                deleteDir()
-                            }
-                        }
-
-                        stage('Cobertura') {
-                            steps {
-                                echo 'COBERTURA STAGE'
+                    steps {
+                        echo 'UNIT STAGE'
+                        script {
+                            if (!unitTestsExecuted) {
+                                unitTestsExecuted = true
+                                // Pytest no tiene la posibilidad de retornar exit=0 cuando algún test falla por lo que abortaría
+                                // el pipeline. Con catchError se captura la salida que devuelve pytest y permite
+                                // seguir con la ejecución del pipeline si falla algún test
                                 catchError(buildResult: 'UNSTABLE', stageResult: 'FAILURE'){
                                     unstash name:'code'
-                                    unstash name:'unit-results'
                                     sh '''
-                                            hostname
-                                            echo ${WORKSPACE}
-                                            coverage xml
+                                        hostname
+                                        echo ${WORKSPACE}
+                                        export PYTHONPATH=${WORKSPACE}
+                                        coverage run --branch --source=app --omit=app/__init__.py,app/api.py -m pytest --junitxml=result-unit.xml test/unit
                                     '''
-                                    recordCoverage qualityGates: [[criticality: 'NOTE', integerThreshold: 95, metric: 'LINE', threshold: 95.0], [criticality: 'ERROR', integerThreshold: 85, metric: 'LINE', threshold: 85.0], [criticality: 'NOTE', integerThreshold: 90, metric: 'BRANCH', threshold: 90.0], [criticality: 'ERROR', integerThreshold: 80, metric: 'BRANCH', threshold: 80.0]], tools: [[parser: 'COBERTURA', pattern: 'coverage.xml']]
-                                     stash name:'coverage-results', includes:'coverage.xml'
+                                    junit 'result-unit.xml'
+                                    stash name:'unit-results', includes:'result-unit.xml,.coverage'
                                 }
-                                // Limpia el workspace del agent al final de la ejecucion
-                                deleteDir()
+                            } else {
+                                echo "El stage ya se ha ejecutado"
                             }
                         }
+                        // Limpia el workspace del agent al final de la ejecucion
+                        deleteDir()
                     }
                 }
 
@@ -164,43 +139,68 @@ pipeline {
                         deleteDir()
                     }
                 }
+            }
+        }
 
-                // agent1: PERFORMANCE (solo y después del paralelo)
-                stage('Performance') {
-                    agent { label 'agent1' }
-                    steps {
-                        echo 'PERFORMANCE STAGE'
-                        catchError(buildResult: 'UNSTABLE', stageResult: 'FAILURE'){
-                            unstash name:'code'
+        // agent1: UNIT + COBERTURA (secuencial)
+        stage('Performance & Coverage') {
+        parallel {
+            stages {
+                    // agent1: PERFORMANCE (solo y después del paralelo)
+                    stage('Performance') {
+                        agent { label 'agent1' }
+                        steps {
+                            echo 'PERFORMANCE STAGE'
+                            catchError(buildResult: 'UNSTABLE', stageResult: 'FAILURE'){
+                                unstash name:'code'
 
-                            sh '''
-                                hostname
-                                echo ${WORKSPACE}
-                                export FLASK_APP=app/api.py
-                                flask run --host=0.0.0.0 &
-                                FLASK_PID=$!
+                                sh '''
+                                    hostname
+                                    echo ${WORKSPACE}
+                                    export FLASK_APP=app/api.py
+                                    flask run --host=0.0.0.0 &
+                                    FLASK_PID=$!
 
-                                
-                                # Intenta matar Flask, y si no puede continua
-                                cleanup() {
-                                  kill "$FLASK_PID" >/dev/null 2>&1 || true 
-                                }
-                                #Cuando el script termine, por el motivo que sea, ejecuta la función cleanup
-                                trap cleanup EXIT 
+                                    
+                                    # Intenta matar Flask, y si no puede continua
+                                    cleanup() {
+                                      kill "$FLASK_PID" >/dev/null 2>&1 || true 
+                                    }
+                                    #Cuando el script termine, por el motivo que sea, ejecuta la función cleanup
+                                    trap cleanup EXIT 
 
-                                sleep 5
-                                /opt/apache-jmeter-5.6.3/bin/jmeter -n -t test/jmeter/flask.jmx -f -l flask.jtl
-                            '''
-                            perfReport sourceDataFiles: 'flask.jtl'
-                            stash name:'performance-results', includes:'flask.jtl'
+                                    sleep 5
+                                    /opt/apache-jmeter-5.6.3/bin/jmeter -n -t test/jmeter/flask.jmx -f -l flask.jtl
+                                '''
+                                perfReport sourceDataFiles: 'flask.jtl'
+                                stash name:'performance-results', includes:'flask.jtl'
+                            }
+                            // Limpia el workspace del agent al final de la ejecucion
+                            deleteDir()
                         }
-                        // Limpia el workspace del agent al final de la ejecucion
-                        deleteDir()
+                    }
+
+                    stage('Cobertura') {
+                        steps {
+                            echo 'COBERTURA STAGE'
+                            catchError(buildResult: 'UNSTABLE', stageResult: 'FAILURE'){
+                                unstash name:'code'
+                                unstash name:'unit-results'
+                                sh '''
+                                        hostname
+                                        echo ${WORKSPACE}
+                                        coverage xml
+                                '''
+                                recordCoverage qualityGates: [[criticality: 'NOTE', integerThreshold: 95, metric: 'LINE', threshold: 95.0], [criticality: 'ERROR', integerThreshold: 85, metric: 'LINE', threshold: 85.0], [criticality: 'NOTE', integerThreshold: 90, metric: 'BRANCH', threshold: 90.0], [criticality: 'ERROR', integerThreshold: 80, metric: 'BRANCH', threshold: 80.0]], tools: [[parser: 'COBERTURA', pattern: 'coverage.xml']]
+                                 stash name:'coverage-results', includes:'coverage.xml'
+                            }
+                            // Limpia el workspace del agent al final de la ejecucion
+                            deleteDir()
+                        }
                     }
                 }
             }
         }
-
 
     }
 }
